version: '2.1'
services:
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./angular/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./angular/dist/KwetterFrontend:/var/www
    depends_on:
      - authentication
      - administrator
      - update_server

  administrator:
    expose:
      - "8080"
    ports:
      - "8081:8080"
    build:
      context: ./adminstrator
      dockerfile: Dockerfile
    depends_on:
      - authentication
      - activemq

  backend_server:
    expose:
      - "8080"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      backend_database:
        condition: service_healthy

  authentication:
    image: kwetter-authentication
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      activemq:
        condition: service_started
      backend_server:
        condition: service_started
      authentication_database:
        condition: service_healthy

  update_server:
    image: kwetter-update
    expose:
      - "8080"
    ports:
      - "8080:8080"
    build:
      context: ./update-server
      dockerfile: Dockerfile
    depends_on:
      - activemq

  authentication_database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jpa_auth'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20

  backend_database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jpa_auth'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20

  activemq:
    image: webcenter/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
